devices:
  sunburst:
    name: Sunburst
    manufacturer: Starchasers
    model: Computer
    identifier: sunburst-base-alpha
    configuration_url: http://10.1.2.133:9090

sensors:
  cpu-temp:
    device_class: temperature
    unit_of_measurement: "°C"
    name: CPU temp
    deviceRef: sunburst
    exec: ./get_cpu_temp
    update:
      every: 5s
      cron: "*/5 * * * *" # every 5 minutes
      only_on_change: true

binary_sensors:
  windows-vm-running:
    device_class: power
    name: Windows VM running
    deviceRef: sunburst
    exec: ./is_windows_vm_running
    update:
      every: 5s
      cron: "*/5 * * * *" # every 5 minutes
      only_on_change: false