devices:
  wm-host:
    name: VM Host PC
    manufacturer: Me
    model: Computer
    identifier: wm-host-computer
    configuration_url: http://localhost

sensors:
  cpu-temp:
    device_class: temperature
    unit_of_measurement: "°C"
    name: CPU temp
    deviceRef: wm-host
    exec: ./get_cpu_temp
    update:
      every: 5s
      cron: "*/5 * * * *" # every 5 minutes
      only_on_change: true

binary_sensors:
  windows-vm-running:
    device_class: power
    name: Windows VM running
    deviceRef: wm-host
    exec: ./is_windows_vm_running
    update:
      every: 5s
      cron: "*/5 * * * *" # every 5 minutes
      only_on_change: false